"use client";
import ScrollLink from "../../components/scrollLink";
export default function Jude1() {
  return (
    <div>
      <h2 className="calibre_14" id="calibre_pb_1321">
        INTRODUCTION
      </h2>
      <h3 className="calibre_15">
        <span className="calibre3">
          <span className="calibre_16">(A.D. 66)</span>
        </span>
      </h3>
      <p className="calibre_18" id="filepos14863678">
        <span className="bold1">
          <sup className="calibre7">1</sup>Jude, t he servant of Jesus Christ,
          and Brother of James{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Jude was the half-brother of the Lord Jesus Christ as well)
              </span>
            </span>
          </span>
          , to them who are Sanctified by God the Father{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (should have been translated, to them who are loved by God the
                Father)
              </span>
            </span>
          </span>
          , and preserved in Jesus Christ{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (in effect, says, God the Father is keeping the Saints guarded
                by Jesus Christ)
              </span>
            </span>
          </span>
          ,{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">and</span>
            </span>
          </span>{" "}
          Called{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the idea, as presented here by the Holy Spirit through Jude, is
                that God does not want to lose the people He has Called to be
                His Own through false doctrine)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">2</sup>Mercy unto you, and Peace, and Love,
          be multiplied{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (all of this is made possible by the Cross, and the Cross alone)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_20">
        <span className="bold1">FALSE TEACHERS</span>
      </p>
      <p className="calibre_18">
        <span className="bold1">
          <sup className="calibre7">3</sup>Beloved, when I gave all diligence{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (a compulsion generated by the Holy Spirit)
              </span>
            </span>
          </span>{" "}
          to write unto you of the common Salvation{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (he had at first thought to write an Epistle similar to Romans,
                but the Holy Spirit, although the Author of the compulsion, did
                not lead in this direction)
              </span>
            </span>
          </span>
          , it was needful for me to write unto you{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the implication is that whatever was to be written had to be
                written at once, and could not be prepared for at leisure)
              </span>
            </span>
          </span>
          , and exhort{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">you</span>
            </span>
          </span>{" "}
          that you should earnestly contend for the Faith{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to the fact that the Saints must defend the Doctrines of
                Christianity with intense effort)
              </span>
            </span>
          </span>{" "}
          which was once delivered unto the Saints{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to the fact that no other Faith will be given; the idea
                is that God gave the Christian Doctrines to the Saints as a
                deposit of Truth to be guarded)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">4</sup>For there are certain men crept in
          unawares{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (false teachers had crept into the Church)
              </span>
            </span>
          </span>
          , who were before of old ordained to this condemnation, ungodly men{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (they came in by stealth and dishonesty; however, their methods
                were by no means new; they would assume an outward expression of
                light)
              </span>
            </span>
          </span>
          , turning the Grace of our God into lasciviousness{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to the fact that Grace had been turned to license)
              </span>
            </span>
          </span>
          , and denying the only Lord God, and our Lord Jesus Christ{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (if we deny the Cross, which is Gods Plan of Redemption, we are
                at the same time denying Both the Father and the Son)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">5</sup>I will therefore put you in
          remembrance{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (suggests something of anxiety and upbraiding, which may be
                compared to the tone of Paul in writing Galatians)
              </span>
            </span>
          </span>
          , though you once knew this, how that the Lord, having saved the
          people out of the Land of Egypt, afterward destroyed them who believed
          not{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (unbelief destroyed the Israelites in the wilderness, and it
                will do the same presently)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21" id="filepos14867336">
        <span className="bold1">
          <sup className="calibre7">6</sup>And the Angels which kept not their
          first estate, but left their own habitation{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (these particular Angels did not maintain their original
                position in which they were created, but transgressed those
                limits to invade territory foreign to them, namely the human
                race; they left Heaven and came to Earth, seeking to cohabit
                with women, which they did [
                <ScrollLink href="/genesis-06" scrollToId="#filepos94308">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Gen. 6:4</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          , He{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(the Lord)</span>
            </span>
          </span>{" "}
          has reserved in everlasting chains under darkness unto the Judgment of
          the Great Day{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (these Angels are now imprisoned [
                <ScrollLink href="/peter2-2" scrollToId="#filepos14756998">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">II Pet. 2:4</span>
                    </span>
                  </span>
                </ScrollLink>
                ], and will be judged at the Great White Throne Judgment, then
                placed in the Lake of Fire where they will remain forever and
                forever [
                <ScrollLink href="/revelation-20" scrollToId="#filepos15128140">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Rev. 20:10</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">7</sup>Even as Sodom and Gomorrha, and the
          cities about them in like manner{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the Greek Text introduces a comparison showing a likeness
                between the Angels of{" "}
                <ScrollLink href="/" scrollToId="#filepos14867336">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Verse 6</span>
                    </span>
                  </span>
                </ScrollLink>{" "}
                and the cities of Sodom and Gomorrah; but the likeness between
                them lies deeper than the fact that both were guilty of
                committing sin; it extends to the fact that both were guilty of
                the same identical sin)
              </span>
            </span>
          </span>
          , giving themselves over to fornication, and going after strange flesh{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the Angels cohabited with women; the sin of Sodom and Gomorrah,
                and the cities around them, was homosexuality [
                <ScrollLink href="/romans-01" scrollToId="#filepos13288191">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Rom. 1:27</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          , are set forth for an example, suffering the vengeance of eternal
          fire{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (those who engage in the sin of homosexuality and refuse to
                repent will suffer the vengeance of the Lake of Fire)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">8</sup>Likewise also these{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">filthy</span>
            </span>
          </span>{" "}
          dreamers defile the flesh{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Jude likens these false teachers to filthy dreamers, and refers
                to their doctrines as being the fruits of mere imagination and
                fancies)
              </span>
            </span>
          </span>
          , despise dominion{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (they refuse to live by the Word of God, but rather fabricate
                their own religion)
              </span>
            </span>
          </span>
          , and speak evil of dignities{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to reviling the Word of God, and more particularly
                Christ and the Cross)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">9</sup>Yet Michael the Archangel{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (no other Angel bears the title of Archangel, as recorded; there
                are others who are Chief Angels, and Michael is only one of them
                [
                <ScrollLink href="/daniel-10" scrollToId="#filepos9907336">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Dan. 10:13</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          , when contending with the Devil he disputed about the body of Moses{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (after the death of Moses, Satan demanded the body of the
                Lawgiver which was denied him by Michael, the Archangel)
              </span>
            </span>
          </span>
          , did not bring against him{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(against Satan)</span>
            </span>
          </span>{" "}
          a railing accusation, but said, The Lord rebuke you{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (a railing accusation would have placed Michael on the same
                level with the Devil to which the great Archangel would not
                stoop, and rightly so!)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">10</sup>But these{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(false teachers)</span>
            </span>
          </span>{" "}
          speak evil of those things which they know not{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the adage here applies, fools rush in where Angels fear to
                tread)
              </span>
            </span>
          </span>
          : but what they know naturally, as brute beasts{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Jude refers to these false teachers as being in the class of
                unreasoning animals)
              </span>
            </span>
          </span>
          , in those things they corrupt themselves{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (could have been translated, by these things are being brought
                to ruin)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">11</sup>Woe unto them!{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Concerning apostasy and apostates, the Holy Spirit says to
                them, Woe!)
              </span>
            </span>
          </span>{" "}
          for they have gone in the way of Cain{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the type of a religious man who believes in God and religion,
                but after his own will, and who rejects Redemption by blood)
              </span>
            </span>
          </span>
          , and ran greed ily after the error of Balaam for reward{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the error of Balaam was that he was blind to the higher
                morality of the Cross, through which God maintains and enforces
                the authority and awful sanctions of His Law, so that He can be
                Just and the Justifier of the believing sinner; he loved the
                wages of unrighteousness in coveting the gifts of Balak [
                <ScrollLink href="/numbers-22" scrollToId="#filepos1961338">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Num. 22:7</span>
                    </span>
                  </span>
                </ScrollLink>
                ,{" "}
                <ScrollLink href="/numbers-22" scrollToId="#filepos1963686">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">17</span>
                    </span>
                  </span>
                </ScrollLink>
                ,{" "}
                <ScrollLink href="/numbers-22" scrollToId="#filepos1971101">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">37</span>
                    </span>
                  </span>
                </ScrollLink>
                ;{" "}
                <ScrollLink href="/numbers-24" scrollToId="#filepos1987291">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">24:11</span>
                    </span>
                  </span>
                </ScrollLink>
                ;{" "}
                <ScrollLink href="/peter2-2" scrollToId="#filepos14765827">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">II Pet. 2:15</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          , and perished in the gainsaying of Core{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the gainsaying of this man was his rebellion against Aaron as
                Gods appointed Priest; this was, in principle, a denial of the
                High Priesthood of Christ [Num., Chpt.{" "}
                <ScrollLink href="/numbers-16" scrollToId="#filepos1880266">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">16</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">12</sup>These are spots{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(rocks)</span>
            </span>
          </span>{" "}
          in your feasts of charity, when they feast with you{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (these false teachers participated in the Lords Supper, thereby,
                claiming to be Godly)
              </span>
            </span>
          </span>
          , feeding themselves without fear{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (furthering their own schemes and lusts instead of tending the
                flock of God)
              </span>
            </span>
          </span>
          : clouds{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">they are</span>
            </span>
          </span>{" "}
          without water{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (such disappoints the ground that needs rain; likewise, these
                false teachers look good outwardly, but inwardly there is no
                substance)
              </span>
            </span>
          </span>
          , carried about of winds{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (they seek Believers with itching ears; they have no true course
                of the Word of God)
              </span>
            </span>
          </span>
          ; trees whose fruit withers, without fruit{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (there is no proper fruit, simply because good fruit cannot come
                from a bad tree)
              </span>
            </span>
          </span>
          , twice dead{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (they were dead in trespasses and sins before being saved, and
                now they have gone back on God and are dead again, i.e., twice
                dead)
              </span>
            </span>
          </span>
          , plucked up by the roots{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (they are not like the true tree planted by the waters)
              </span>
            </span>
          </span>
          ;
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">13</sup>Raging waves of the sea{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to the destruction caused by false doctrine)
              </span>
            </span>
          </span>
          , foaming out their own shame{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (false doctrine is like the foam or scum at the seashore)
              </span>
            </span>
          </span>
          ; wandering stars{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (an unpredictable star which provides no guidance for
                navigation)
              </span>
            </span>
          </span>
          , to whom is reserved the blackness of darkness forever{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to their eternal doom [
                <ScrollLink href="/peter2-2" scrollToId="#filepos14756998">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">II Pet. 2:4</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21" id="filepos14875780">
        <span className="bold1">
          <sup className="calibre7">14</sup>And Enoch also, the seventh from
          Adam{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the Old Testament person of that name, the man who walked with
                God [
                <ScrollLink href="/genesis-05" scrollToId="#filepos85067">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Gen. 5:18-24</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          , Prophesied of these{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the translation should read, Prophesied with respect to these
                false teachers of these last days)
              </span>
            </span>
          </span>
          , saying, Behold, the Lord comes with ten thousands of His Saints{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (is actually, His Holy ten thousands, which literally means an
                unlimited number; this quotation is taken from the Book of
                Enoch, which was lost for many centuries with the exception of a
                few fragments, but was found in its entirety in a copy of the
                Ethiopia Bible in 1773)
              </span>
            </span>
          </span>
          ,
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">15</sup>To execute Judgment upon all{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to Christ Judging the nations of the world, which will
                commence at the beginning of the Millennial Reign)
              </span>
            </span>
          </span>
          , and to convince all who are ungodly among them of all their ungodly
          deeds which they have ungodly committed{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the word ungodly is used four times in this Verse, telling us
                that the ungodliness is total; as well, all is used four times,
                which means that none will escape this Judgment)
              </span>
            </span>
          </span>
          , and of all their hard{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">speeches</span>
            </span>
          </span>{" "}
          which ungodly sinners have spoken against Him{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (every ungodly statement against Christ will be addressed at
                that time)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">16</sup>These are murmurers, complainers,
          walking after their own lusts{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Jude has in mind men who cannot get enough to satisfy their
                lusts, and thus complain)
              </span>
            </span>
          </span>
          ; and their mouth speaks great swelling{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">words,</span>
            </span>
          </span>{" "}
          having mens persons in admiration because of advantage{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to showing respect of person; they use flattery for the
                sake of profit)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_20">
        <span className="bold1">EXHORTATIONS</span>
      </p>
      <p className="calibre_18">
        <span className="bold1">
          <sup className="calibre7">17</sup>But, beloved, remember ye the words
          which were spoken before of the Apostles of our Lord Jesus Christ{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (actually refers to that given by Peter and others)
              </span>
            </span>
          </span>
          ;
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">18</sup>How that they told you there should
          be mockers in the last time{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to the last days, in fact, the very time in which we now
                live)
              </span>
            </span>
          </span>
          , who should walk after their own ungodly lusts{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to charting a course which is not of God, but rather
                after the flesh; they have forsaken the Cross!)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">19</sup>These be they who separate
          themselves{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (should be translated, these be they who separate; they have
                forsaken the Cross, purposely choosing another way)
              </span>
            </span>
          </span>
          , sensual{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to that which is not of the Spirit, but rather of the
                flesh)
              </span>
            </span>
          </span>
          , having not the Spirit{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (refers to those who operate outside the Cross of Christ)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">20</sup>But you, Beloved{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (contrasts the Saints with the false teachers)
              </span>
            </span>
          </span>
          , building up yourselves{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (to build toward the finish of the structure for which the
                foundation has already been laid)
              </span>
            </span>
          </span>{" "}
          on your most Holy Faith{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Jesus Christ and Him Crucified)
              </span>
            </span>
          </span>
          , praying in the Holy Spirit{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (our praying must be exercised in the sphere of the Holy Spirit,
                motivated and empowered by Him)
              </span>
            </span>
          </span>
          ,
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">21</sup>Keep yourselves in the Love of God{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (we are to see to it that we stay within the circle of His Love,
                which can only be done by Faith constantly making the Cross its
                Object)
              </span>
            </span>
          </span>
          , looking for the Mercy of our Lord Jesus Christ unto Eternal Life{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (looking for the Rapture of the Church, with all of this made
                possible by what Jesus did on the Cross)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">22</sup>And of some have compassion, making
          a difference{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the false teachers should be addressed on a case by case
                situation, referring to the fact that some have to be handled
                differently than others; some with compassion)
              </span>
            </span>
          </span>
          :
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">23</sup>And others save with fear{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (this particular group needs to be dealt with directly and
                vigorously)
              </span>
            </span>
          </span>
          , pulling{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">them</span>
            </span>
          </span>{" "}
          out of the fire{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(the fire of destruction)</span>
            </span>
          </span>
          ; hating even the garment spotted by the flesh{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (presents works of the flesh, which always characterize those
                who follow a direction other than the Cross)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <p className="calibre_20">
        <span className="bold1">BENEDICTION</span>
      </p>
      <p className="calibre_18" id="filepos14881492">
        <span className="bold1">
          <sup className="calibre7">24</sup>Now unto Him Who is able to keep you
          from falling{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (as weve repeatedly stated, Christ is the Source of all things,
                but the Cross is the means)
              </span>
            </span>
          </span>
          , and to present{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">you</span>
            </span>
          </span>{" "}
          faultless before the Presence of His Glory with exceeding joy{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (the Holy Spirit will, at the appointed time, present us to the
                Father, and will do so with exceeding joy; this refers to the
                Believer standing blameless before the Judgment Seat, all
                because of Christ and what He did at the Cross [
                <ScrollLink href="/colossians-1" scrollToId="#filepos14146396">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Col. 1:22</span>
                    </span>
                  </span>
                </ScrollLink>
                ;{" "}
                <ScrollLink
                  href="/thessalonians1-2"
                  scrollToId="#filepos14208003"
                >
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">I Thess. 3:13</span>
                    </span>
                  </span>
                </ScrollLink>
                ])
              </span>
            </span>
          </span>
          ,
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">25</sup>To the only wise God our Saviour{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">(speaks of the Cross)</span>
            </span>
          </span>
          ,{" "}
          <span className="italic1">
            <span>
              <span className="calibre_19">be</span>
            </span>
          </span>{" "}
          Glory and Majesty, Dominion and Power, both now and ever. Amen{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (every Believer will share in all of this, and do so forever;
                once again, all because of the Cross)
              </span>
            </span>
          </span>
          .
        </span>
      </p>
      <div className="mbp_pagebreak" id="calibre_pb_1322"></div>
    </div>
  );
}
