"use client";
import ScrollLink from "../../components/scrollLink";
export default function Proverbs04() {
  return (
    <div>
      <h3 className="calibre_15" id="filepos6750470">
        CHAPTER 4
      </h3>
      <h3 className="calibre_17">(1000 B.C.)</h3>
      <p className="calibre_20">
        <span className="bold1">A FATHERS WISDOM AND ADVICE</span>
      </p>
      <p className="calibre_18">
        <span className="bold1">
          <sup className="calibre7">1</sup>Hear, you children, the instruction
          of a father, and attend to know understanding.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (We will now learn the source of this great Wisdom, which will
                prove extremely interesting.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">2</sup>For I give you good doctrine, forsake
          you not my law.
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">3</sup>For I was my fathers son, tender and
          only beloved in the sight of my mother.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Solomon was speaking of his father, David, and his mother,
                Bath-sheba. He claims to have received the doctrine and the Law
                from David; therefore, in these Passages we have the manner in
                which the Holy Spirit chose regarding Solomons great Wisdom.
                Along with what David taught him, which, of course, was
                generated by the Holy Spirit, likewise, the Lord gave Solomon
                the great Gift of Wisdom [
                <ScrollLink href="/kings1-03" scrollToId="#filepos3723487">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">I Ki. 3:9-15</span>
                    </span>
                  </span>
                </ScrollLink>
                ].)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">4</sup>He taught me also, and said unto me,
          Let your heart retain my words: keep my commandments, and live.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Solomon recalls the countless hours that David painstakingly
                taught him the Ways of the Lord.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">5</sup>Get wisdom, get understanding: forget
          it not; neither decline from the words of my mouth.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (This Wisdom consisted of what David taught his son, Solomon,
                which was derived from the Word of God. At this time, David
                would have had as his Bible the Pentateuch [Genesis through
                Deuteronomy], as well as Joshua, Judges, and possibly Ruth.
                There is every evidence that Solomon was well versed in the
                great Law of Moses.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">6</sup>Forsake her not, and she shall
          preserve you: love her, and she shall keep you.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Solomon would heed these words for the greater part of his
                life; however, in the latter part of his reign, he would do what
                David had admonished him not to do, which was to forget and
                forsake the Ways of the Lord [
                <ScrollLink href="/kings1-11" scrollToId="#filepos3849589">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">I Ki. 11:4</span>
                    </span>
                  </span>
                </ScrollLink>
                ].)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">7</sup>Wisdom is the principal thing;
          therefore get wisdom: and with all your getting get understanding.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (There are six different Hebrew words translated Wisdom. We have
                likened Wisdom and the Bible as one and the same; however, in
                the strict and narrow interpretation of the word, this would not
                be totally correct. It would more so apply to the comprehension
                and understanding of the Bible. Still, without the Bible, there
                can be no Wisdom.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">8</sup>Exalt her, and she shall promote you:
          she shall bring you to honour, when you do embrace her.
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">9</sup>She shall give to your head an
          ornament of grace: a crown of glory shall she deliver to you.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Without fail, we are told that Wisdom [the Bible] will fulfill
                the cry of the human heart. It is sad when even the Church
                little exalts the Bible, but, rather, promotes the works of
                man.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">10</sup>Hear, O my son, and receive my
          sayings; and the years of your life shall be many.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (While it is certainly true that things seen with the eye are
                important, still, the way the Gospel is imparted is by the
                hearing of the ear [
                <ScrollLink href="/matthew-11" scrollToId="#filepos10990930">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Mat. 11:15</span>
                    </span>
                  </span>
                </ScrollLink>
                ].)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">11</sup>I have taught you in the way of
          wisdom; I have led you in right paths.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The Way of Wisdom and the Right Paths are the Bible. The
                tragedy is that no one but Christ has ever faithfully walked the
                Right Paths.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">12</sup>When you go, your steps shall not be
          straitened; and when you run, you shall not stumble.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (This Verse should read, When you walk and if you run. To walk
                is obligatory; to run is optional. Wisdom secures both. When
                walking, the way opens it is not straitened; if running, the
                feet are guarded from stumbling [Jude,{" "}
                <ScrollLink href="/" scrollToId="#filepos6758769">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Vs. 24</span>
                    </span>
                  </span>
                </ScrollLink>
                ].)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">13</sup>Take fast hold of instruction; let
          her not go: keep her; for she is your life.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (This refers to the Truth that the Bible, and the Bible alone,
                holds the secret of eternal life.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">14</sup>Enter not into the path of the
          wicked, and go not in the way of evil men.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The inference is that the path of the wicked constantly
                beckons.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">15</sup>Avoid it, pass not by it, turn from
          it, and pass away.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The Holy Spirit is emphatic in giving us a fourfold warning.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">16</sup>For they sleep not, except they have
          done mischief; and their sleep is taken away, unless they cause some
          to fall.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (We are told here that spiritual vigilance is ever required.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">17</sup>For they eat the bread of
          wickedness, and drink the wine of violence.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Such who follow this path of evil always conclude in wickedness
                and violence.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">18</sup>But the path of the just is as the
          shining light, that shines more and more unto the perfect day.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The Word of God alone leads to that perfect day.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">19</sup>The way of the wicked is as
          darkness: they know not at what they stumble.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The Bible is the only Light [
                <ScrollLink href="/psalm-119" scrollToId="#filepos6570898">
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">Ps. 119:105</span>
                    </span>
                  </span>
                </ScrollLink>
                ]. Everything else is darkness, irrespective of its claims, and
                induces stumbling.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">20</sup>My son, attend to my words; incline
          your ear unto my sayings.
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">21</sup>Let them not depart from your eyes;
          keep them in the midst of your heart.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (We are admonished here to continue to read the Bible and to
                study it daily. As well, its teachings are to embed themselves
                into our hearts.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">22</sup>For they are life unto those who
          find them, and health to all their flesh.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (In these Passages, we learn the secret of life. The Word of God
                is Life and Health.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">23</sup>Keep your heart with all diligence;
          for out of it are the issues of life.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The issues of life speak of the Foundation of the Faith, which
                is Jesus Christ and Him Crucified [
                <ScrollLink
                  href="/corinthians1-01"
                  scrollToId="#filepos13546910"
                >
                  <span className="calibre_19">
                    <span>
                      <span className="calibre_19">I Cor. 1:23</span>
                    </span>
                  </span>
                </ScrollLink>
                ].)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21" id="filepos6758769">
        <span className="bold1">
          <sup className="calibre7">24</sup>Put away from you a froward mouth,
          and perverse lips put far from you.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The word froward means to be habitually disposed toward
                disobedience and opposition to the Word of God. The word
                perverse means basically the same. So we are told here not to
                question the Bible, find fault with it, or oppose it.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">25</sup>Let your eyes look right on, and let
          your eyelids look straight before you.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (Irrespective of the attractions that may try to draw us away,
                our eyes must continue to look to the Word of God.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">26</sup>Ponder the path of your feet, and
          let all your ways be established.
        </span>
      </p>
      <p className="calibre_21">
        <span className="bold1">
          <sup className="calibre7">27</sup>Turn not to the right hand nor to
          the left: remove your foot from evil.{" "}
          <span className="italic1">
            <span>
              <span className="explanation">
                (The word ponder means to prayerfully weigh, that is, not to
                enter hastily upon any course of conduct.)
              </span>
            </span>
          </span>
        </span>
      </p>
      <div className="mbp_pagebreak" id="calibre_pb_688"></div>
    </div>
  );
}
