export const BooksOfTheBible = [
  {
    name: "Genesis",
    title: "THE FIRST BOOK OF MOSES",
    numberOfChapters: 50,
    href: "/genesis",
  },
  {
    name: "Exodus",
    title: "THE SECOND BOOK OF MOSES",
    numberOfChapters: 40,
    href: "/exodus",
  },
  {
    name: "Leviticus",
    title: "THE THIRD BOOK OF MOSES",
    numberOfChapters: 27,
    href: "/leviticus",
  },
  {
    name: "Numbers",
    title: "THE FOURTH BOOK OF MOSES",
    numberOfChapters: 36,
    href: "/numbers",
  },
  {
    name: "Deuteronomy",
    title: "THE FIFTH BOOK OF MOSES",
    numberOfChapters: 34,
    href: "/deuteronomy",
  },
  {
    name: "Joshua",
    title: "THE BOOK OF JOSHUA",
    numberOfChapters: 24,
    href: "/joshua",
  },
  {
    name: "Judges",
    title: "THE BOOK OF JUDGES",
    numberOfChapters: 21,
    href: "/judges",
  },
  {
    name: "Ruth",
    title: "THE BOOK OF RUTH",
    numberOfChapters: 4,
    href: "/ruth",
  },
  {
    name: "1 Samuel",
    title: "THE FIRST BOOK OF SAMUEL",
    numberOfChapters: 31,
    href: "/samuel1",
  },
  {
    name: "2 Samuel",
    title: "THE SECOND BOOK OF SAMUEL",
    numberOfChapters: 24,
    href: "/samuel2",
  },
  {
    name: "1 Kings",
    title: "THE FIRST BOOK OF KINGS",
    numberOfChapters: 22,
    href: "/kings1",
  },
  {
    name: "2 Kings",
    title: "THE SECOND BOOK OF KINGS",
    numberOfChapters: 25,
    href: "/kings2",
  },
  {
    name: "1 Chronicles",
    title: "THE FIRST BOOK OF CHRONICLES",
    numberOfChapters: 29,
    href: "/chronicles1",
  },
  {
    name: "2 Chronicles",
    title: "THE SECOND BOOK OF CHRONICLES",
    numberOfChapters: 36,
    href: "/chronicles2",
  },
  {
    name: "Ezra",
    title: "THE BOOK OF EZRA",
    numberOfChapters: 10,
    href: "/ezra",
  },
  {
    name: "Nehemiah",
    title: "THE BOOK OF NEHEMIAH",
    numberOfChapters: 13,
    href: "/nehemiah",
  },
  {
    name: "Esther",
    title: "THE BOOK OF ESTHER",
    numberOfChapters: 10,
    href: "/esther",
  },
  {
    name: "Job",
    title: "THE BOOK OF JOB",
    numberOfChapters: 42,
    href: "/job",
  },
  {
    name: "Psalms",
    title: "THE BOOK OF PSALMS",
    numberOfChapters: 150,
    href: "/psalms",
  },
  {
    name: "Proverbs",
    title: "THE BOOK OF PROVERBS",
    numberOfChapters: 31,
    href: "/proverbs",
  },
  {
    name: "Ecclesiastes",
    title: "THE BOOK OF ECCLESIASTES",
    numberOfChapters: 12,
    href: "/ecclesiastes",
  },
  {
    name: "Songs of Solomon",
    title: "THE SONGS OF SOLOMON",
    numberOfChapters: 8,
    href: "/songsofsolomon",
  },
  {
    name: "Isaiah",
    title: "THE BOOK OF ISAIAH",
    numberOfChapters: 66,
    href: "/isaiah",
  },
  {
    name: "Jeremiah",
    title: "THE BOOK OF JEREMIAH",
    numberOfChapters: 52,
    href: "/jeremiah",
  },
  {
    name: "Lamentations",
    title: "THE LAMENTATIONS OF JEREMIAH",
    numberOfChapters: 5,
    href: "/lamentations",
  },
  {
    name: "Ezekiel",
    title: "THE BOOK OF EZEKIEL",
    numberOfChapters: 48,
    href: "/ezekiel",
  },
  {
    name: "Daniel",
    title: "THE BOOK OF DANIEL",
    numberOfChapters: 12,
    href: "/daniel",
  },
  {
    name: "Hosea",
    title: "THE BOOK OF HOSEA",
    numberOfChapters: 14,
    href: "/hosea",
  },
  {
    name: "Joel",
    title: "THE BOOK OF JOEL",
    numberOfChapters: 3,
    href: "/joel",
  },
  {
    name: "Amos",
    title: "THE BOOK OF AMOS",
    numberOfChapters: 9,
    href: "/amos",
  },
  {
    name: "Obadiah",
    title: "THE BOOK OF OBADIAH",
    numberOfChapters: 1,
    href: "/obadiah",
  },
  {
    name: "Jonah",
    title: "THE BOOK OF JONAH",
    numberOfChapters: 4,
    href: "/jonah",
  },
  {
    name: "Micah",
    title: "THE BOOK OF MICAH",
    numberOfChapters: 7,
    href: "/micah",
  },
  {
    name: "Nahum",
    title: "THE BOOK OF NAHUM",
    numberOfChapters: 3,
    href: "/nahum",
  },
  {
    name: "Habakkuk",
    title: "THE BOOK OF HABAKKUK",
    numberOfChapters: 3,
    href: "/habakkuk",
  },
  {
    name: "Zephaniah",
    title: "THE BOOK OF ZEPHANIAH",
    numberOfChapters: 3,
    href: "/zephaniah",
  },
  {
    name: "Haggai",
    title: "THE BOOK OF HAGGAI",
    numberOfChapters: 2,
    href: "/haggai",
  },
  {
    name: "Zechariah",
    title: "THE BOOK OF ZECHARIAH",
    numberOfChapters: 14,
    href: "/zechariah",
  },
  {
    name: "Malachi",
    title: "THE BOOK OF MALACHI",
    numberOfChapters: 4,
    href: "/malachi",
  },
  {
    name: "Matthew",
    title: "THE GOSPEL ACCORDING TO MATTHEW",
    numberOfChapters: 28,
    href: "/matthew",
  },
  {
    name: "Mark",
    title: "THE GOSPEL ACCORDING TO MARK",
    numberOfChapters: 16,
    href: "/mark",
  },
  {
    name: "Luke",
    title: "THE GOSPEL ACCORDING TO LUKE",
    numberOfChapters: 24,
    href: "/luke",
  },
  {
    name: "John",
    title: "THE GOSPEL ACCORDING TO JOHN",
    numberOfChapters: 21,
    href: "/john",
  },
  {
    name: "Acts",
    title: "THE ACTS OF THE APOSTLES",
    numberOfChapters: 28,
    href: "/acts",
  },
  {
    name: "Romans",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE ROMANS",
    numberOfChapters: 16,
    href: "/romans",
  },
  {
    name: "1 Corinthians",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
    numberOfChapters: 16,
    href: "/corinthians1",
  },
  {
    name: "2 Corinthians",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
    numberOfChapters: 13,
    href: "/corinthians2",
  },
  {
    name: "Galatians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE GALATIANS",
    numberOfChapters: 6,
    href: "/galatians",
  },
  {
    name: "Ephesians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE EPHESIANS",
    numberOfChapters: 6,
    href: "/ephesians",
  },
  {
    name: "Philippians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE PHILIPPIANS",
    numberOfChapters: 4,
    href: "/philippians",
  },
  {
    name: "Colossians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE COLOSSIANS",
    numberOfChapters: 4,
    href: "/colossians",
  },
  {
    name: "1 Thessalonians",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
    numberOfChapters: 5,
    href: "/thessalonians1",
  },
  {
    name: "2 Thessalonians",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
    numberOfChapters: 3,
    href: "/thessalonians2",
  },
  {
    name: "1 Timothy",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
    numberOfChapters: 6,
    href: "/timothy1",
  },
  {
    name: "2 Timothy",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
    numberOfChapters: 4,
    href: "/timothy2",
  },
  {
    name: "Titus",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO TITUS",
    numberOfChapters: 3,
    href: "/titus",
  },
  {
    name: "Philemon",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO PHILEMON",
    numberOfChapters: 1,
    href: "/philemon",
  },
  {
    name: "Hebrews",
    title: "THE EPISTLE TO THE HEBREWS",
    numberOfChapters: 13,
    href: "/hebrews",
  },
  {
    name: "James",
    title: "THE EPISTLE OF JAMES",
    numberOfChapters: 5,
    href: "/james",
  },
  {
    name: "1 Peter",
    title: "THE FIRST EPISTLE OF PETER",
    numberOfChapters: 5,
    href: "/peter1",
  },
  {
    name: "2 Peter",
    title: "THE SECOND EPISTLE OF PETER",
    numberOfChapters: 3,
    href: "/peter2",
  },
  {
    name: "1 John",
    title: "THE FIRST EPISTLE OF JOHN",
    numberOfChapters: 5,
    href: "/john1",
  },
  {
    name: "2 John",
    title: "THE SECOND EPISTLE OF JOHN",
    numberOfChapters: 1,
    href: "/john2",
  },
  {
    name: "3 John",
    title: "THE THIRD EPISTLE OF JOHN",
    numberOfChapters: 1,
    href: "/john3",
  },
  {
    name: "Jude",
    title: "THE GENERAL EPISTLE OF JUDE",
    numberOfChapters: 1,
    href: "/jude",
  },
  {
    name: "Revelation",
    title: "THE REVELATION OF JESUS CHRIST",
    numberOfChapters: 22,
    href: "/revelation",
  },
];

export const OldTestamentBooks = [
  {
    name: "Genesis",
    title: "THE FIRST BOOK OF MOSES",
    numberOfChapters: 50,
    href: "/genesis",
  },
  {
    name: "Exodus",
    title: "THE SECOND BOOK OF MOSES",
    numberOfChapters: 40,
    href: "/exodus",
  },
  {
    name: "Leviticus",
    title: "THE THIRD BOOK OF MOSES",
    numberOfChapters: 27,
    href: "/leviticus",
  },
  {
    name: "Numbers",
    title: "THE FOURTH BOOK OF MOSES",
    numberOfChapters: 36,
    href: "/numbers",
  },
  {
    name: "Deuteronomy",
    title: "THE FIFTH BOOK OF MOSES",
    numberOfChapters: 34,
    href: "/deuteronomy",
  },
  {
    name: "Joshua",
    title: "THE BOOK OF JOSHUA",
    numberOfChapters: 24,
    href: "/joshua",
  },
  {
    name: "Judges",
    title: "THE BOOK OF JUDGES",
    numberOfChapters: 21,
    href: "/judges",
  },
  {
    name: "Ruth",
    title: "THE BOOK OF RUTH",
    numberOfChapters: 4,
    href: "/ruth",
  },
  {
    name: "1 Samuel",
    title: "THE FIRST BOOK OF SAMUEL",
    numberOfChapters: 31,
    href: "/samuel1",
  },
  {
    name: "2 Samuel",
    title: "THE SECOND BOOK OF SAMUEL",
    numberOfChapters: 24,
    href: "/samuel2",
  },
  {
    name: "1 Kings",
    title: "THE FIRST BOOK OF KINGS",
    numberOfChapters: 22,
    href: "/kings1",
  },
  {
    name: "2 Kings",
    title: "THE SECOND BOOK OF KINGS",
    numberOfChapters: 25,
    href: "/kings2",
  },
  {
    name: "1 Chronicles",
    title: "THE FIRST BOOK OF CHRONICLES",
    numberOfChapters: 29,
    href: "/chronicles1",
  },
  {
    name: "2 Chronicles",
    title: "THE SECOND BOOK OF CHRONICLES",
    numberOfChapters: 36,
    href: "/chronicles2",
  },
  {
    name: "Ezra",
    title: "THE BOOK OF EZRA",
    numberOfChapters: 10,
    href: "/ezra",
  },
  {
    name: "Nehemiah",
    title: "THE BOOK OF NEHEMIAH",
    numberOfChapters: 13,
    href: "/nehemiah",
  },
  {
    name: "Esther",
    title: "THE BOOK OF ESTHER",
    numberOfChapters: 10,
    href: "/esther",
  },
  {
    name: "Job",
    title: "THE BOOK OF JOB",
    numberOfChapters: 42,
    href: "/job",
  },
  {
    name: "Psalms",
    title: "THE BOOK OF PSALMS",
    numberOfChapters: 150,
    href: "/psalms",
  },
  {
    name: "Proverbs",
    title: "THE BOOK OF PROVERBS",
    numberOfChapters: 31,
    href: "/proverbs",
  },
  {
    name: "Ecclesiastes",
    title: "THE BOOK OF ECCLESIASTES",
    numberOfChapters: 12,
    href: "/ecclesiastes",
  },
  {
    name: "Songs of Solomon",
    title: "THE SONGS OF SOLOMON",
    numberOfChapters: 8,
    href: "/songsofsolomon",
  },
  {
    name: "Isaiah",
    title: "THE BOOK OF ISAIAH",
    numberOfChapters: 66,
    href: "/isaiah",
  },
  {
    name: "Jeremiah",
    title: "THE BOOK OF JEREMIAH",
    numberOfChapters: 52,
    href: "/jeremiah",
  },
  {
    name: "Lamentations",
    title: "THE LAMENTATIONS OF JEREMIAH",
    numberOfChapters: 5,
    href: "/lamentations",
  },
  {
    name: "Ezekiel",
    title: "THE BOOK OF EZEKIEL",
    numberOfChapters: 48,
    href: "/ezekiel",
  },
  {
    name: "Daniel",
    title: "THE BOOK OF DANIEL",
    numberOfChapters: 12,
    href: "/daniel",
  },
  {
    name: "Hosea",
    title: "THE BOOK OF HOSEA",
    numberOfChapters: 14,
    href: "/hosea",
  },
  {
    name: "Joel",
    title: "THE BOOK OF JOEL",
    numberOfChapters: 3,
    href: "/joel",
  },
  {
    name: "Amos",
    title: "THE BOOK OF AMOS",
    numberOfChapters: 9,
    href: "/amos",
  },
  {
    name: "Obadiah",
    title: "THE BOOK OF OBADIAH",
    numberOfChapters: 1,
    href: "/obadiah",
  },
  {
    name: "Jonah",
    title: "THE BOOK OF JONAH",
    numberOfChapters: 4,
    href: "/jonah",
  },
  {
    name: "Micah",
    title: "THE BOOK OF MICAH",
    numberOfChapters: 7,
    href: "/micah",
  },
  {
    name: "Nahum",
    title: "THE BOOK OF NAHUM",
    numberOfChapters: 3,
    href: "/nahum",
  },
  {
    name: "Habakkuk",
    title: "THE BOOK OF HABAKKUK",
    numberOfChapters: 3,
    href: "/habakkuk",
  },
  {
    name: "Zephaniah",
    title: "THE BOOK OF ZEPHANIAH",
    numberOfChapters: 3,
    href: "/zephaniah",
  },
  {
    name: "Haggai",
    title: "THE BOOK OF HAGGAI",
    numberOfChapters: 2,
    href: "/haggai",
  },
  {
    name: "Zechariah",
    title: "THE BOOK OF ZECHARIAH",
    numberOfChapters: 14,
    href: "/zechariah",
  },
  {
    name: "Malachi",
    title: "THE BOOK OF MALACHI",
    numberOfChapters: 4,
    href: "/malachi",
  },
];

export const NewTestamentBooks = [
  {
    name: "Matthew",
    title: "THE GOSPEL ACCORDING TO MATTHEW",
    numberOfChapters: 28,
    href: "/matthew",
  },
  {
    name: "Mark",
    title: "THE GOSPEL ACCORDING TO MARK",
    numberOfChapters: 16,
    href: "/mark",
  },
  {
    name: "Luke",
    title: "THE GOSPEL ACCORDING TO LUKE",
    numberOfChapters: 24,
    href: "/luke",
  },
  {
    name: "John",
    title: "THE GOSPEL ACCORDING TO JOHN",
    numberOfChapters: 21,
    href: "/john",
  },
  {
    name: "Acts",
    title: "THE ACTS OF THE APOSTLES",
    numberOfChapters: 28,
    href: "/acts",
  },
  {
    name: "Romans",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE ROMANS",
    numberOfChapters: 16,
    href: "/romans",
  },
  {
    name: "1 Corinthians",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
    numberOfChapters: 16,
    href: "/corinthians1",
  },
  {
    name: "2 Corinthians",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
    numberOfChapters: 13,
    href: "/corinthians2",
  },
  {
    name: "Galatians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE GALATIANS",
    numberOfChapters: 6,
    href: "/galatians",
  },
  {
    name: "Ephesians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE EPHESIANS",
    numberOfChapters: 6,
    href: "/ephesians",
  },
  {
    name: "Philippians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE PHILIPPIANS",
    numberOfChapters: 4,
    href: "/philippians",
  },
  {
    name: "Colossians",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO THE COLOSSIANS",
    numberOfChapters: 4,
    href: "/colossians",
  },
  {
    name: "1 Thessalonians",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
    numberOfChapters: 5,
    href: "/thessalonians1",
  },
  {
    name: "2 Thessalonians",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
    numberOfChapters: 3,
    href: "/thessalonians2",
  },
  {
    name: "1 Timothy",
    title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
    numberOfChapters: 6,
    href: "/timothy1",
  },
  {
    name: "2 Timothy",
    title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
    numberOfChapters: 4,
    href: "/timothy2",
  },
  {
    name: "Titus",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO TITUS",
    numberOfChapters: 3,
    href: "/titus",
  },
  {
    name: "Philemon",
    title: "THE EPISTLE OF PAUL THE APOSTLE TO PHILEMON",
    numberOfChapters: 1,
    href: "/philemon",
  },
  {
    name: "Hebrews",
    title: "THE EPISTLE TO THE HEBREWS",
    numberOfChapters: 13,
    href: "/hebrews",
  },
  {
    name: "James",
    title: "THE EPISTLE OF JAMES",
    numberOfChapters: 5,
    href: "/james",
  },
  {
    name: "1 Peter",
    title: "THE FIRST EPISTLE OF PETER",
    numberOfChapters: 5,
    href: "/peter1",
  },
  {
    name: "2 Peter",
    title: "THE SECOND EPISTLE OF PETER",
    numberOfChapters: 3,
    href: "/peter2",
  },
  {
    name: "1 John",
    title: "THE FIRST EPISTLE OF JOHN",
    numberOfChapters: 5,
    href: "/john1",
  },
  {
    name: "2 John",
    title: "THE SECOND EPISTLE OF JOHN",
    numberOfChapters: 1,
    href: "/john2",
  },
  {
    name: "3 John",
    title: "THE THIRD EPISTLE OF JOHN",
    numberOfChapters: 1,
    href: "/john3",
  },
  {
    name: "Jude",
    title: "THE GENERAL EPISTLE OF JUDE",
    numberOfChapters: 1,
    href: "/jude",
  },
  {
    name: "Revelation",
    title: "THE REVELATION OF JESUS CHRIST",
    numberOfChapters: 22,
    href: "/revelation",
  },
];

export const BooksOfTheBibleAtoZ = new Map([
  [
    "A",
    [
      {
        name: "Amos",
        title: "THE BOOK OF AMOS",
        numberOfChapters: 9,
        href: "/amos",
      },
      {
        name: "Acts",
        title: "THE ACTS OF THE APOSTLES",
        numberOfChapters: 28,
        href: "/acts",
      },
    ],
  ],
  [
    "C",
    [
      {
        name: "1 Chronicles",
        title: "THE FIRST BOOK OF CHRONICLES",
        numberOfChapters: 29,
        href: "/chronicles1",
      },
      {
        name: "2 Chronicles",
        title: "THE SECOND BOOK OF CHRONICLES",
        numberOfChapters: 36,
        href: "/chronicles2",
      },
      {
        name: "1 Corinthians",
        title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
        numberOfChapters: 16,
        href: "/corinthians1",
      },
      {
        name: "2 Corinthians",
        title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE CORINTHIANS",
        numberOfChapters: 13,
        href: "/corinthians2",
      },
      {
        name: "Colossians",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO THE COLOSSIANS",
        numberOfChapters: 4,
        href: "/colossians",
      },
    ],
  ],
  [
    "D",
    [
      {
        name: "Deuteronomy",
        title: "THE FIFTH BOOK OF MOSES",
        numberOfChapters: 34,
        href: "/deuteronomy",
      },
      {
        name: "Daniel",
        title: "THE BOOK OF DANIEL",
        numberOfChapters: 12,
        href: "/daniel",
      },
    ],
  ],
  [
    "E",
    [
      {
        name: "Exodus",
        title: "THE SECOND BOOK OF MOSES",
        numberOfChapters: 40,
        href: "/exodus",
      },
      {
        name: "Ezra",
        title: "THE BOOK OF EZRA",
        numberOfChapters: 10,
        href: "/ezra",
      },
      {
        name: "Esther",
        title: "THE BOOK OF ESTHER",
        numberOfChapters: 10,
        href: "/esther",
      },
      {
        name: "Ecclesiastes",
        title: "THE BOOK OF ECCLESIASTES",
        numberOfChapters: 12,
        href: "/ecclesiastes",
      },
      {
        name: "Ezekiel",
        title: "THE BOOK OF EZEKIEL",
        numberOfChapters: 48,
        href: "/ezekiel",
      },
      {
        name: "Ephesians",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO THE EPHESIANS",
        numberOfChapters: 6,
        href: "/ephesians",
      },
    ],
  ],
  [
    "G",
    [
      {
        name: "Genesis",
        title: "THE FIRST BOOK OF MOSES",
        numberOfChapters: 50,
        href: "/genesis",
      },
      {
        name: "Galatians",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO THE GALATIANS",
        numberOfChapters: 6,
        href: "/galatians",
      },
    ],
  ],
  [
    "H",
    [
      {
        name: "Hosea",
        title: "THE BOOK OF HOSEA",
        numberOfChapters: 14,
        href: "/hosea",
      },
      {
        name: "Habakkuk",
        title: "THE BOOK OF HABAKKUK",
        numberOfChapters: 3,
        href: "/habakkuk",
      },
      {
        name: "Haggai",
        title: "THE BOOK OF HAGGAI",
        numberOfChapters: 2,
        href: "/haggai",
      },
      {
        name: "Hebrews",
        title: "THE EPISTLE TO THE HEBREWS",
        numberOfChapters: 13,
        href: "/hebrews",
      },
    ],
  ],
  [
    "I",
    [
      {
        name: "Isaiah",
        title: "THE BOOK OF ISAIAH",
        numberOfChapters: 66,
        href: "/isaiah",
      },
    ],
  ],
  [
    "J",
    [
      {
        name: "Joshua",
        title: "THE BOOK OF JOSHUA",
        numberOfChapters: 24,
        href: "/joshua",
      },
      {
        name: "Judges",
        title: "THE BOOK OF JUDGES",
        numberOfChapters: 21,
        href: "/judges",
      },
      {
        name: "Job",
        title: "THE BOOK OF JOB",
        numberOfChapters: 42,
        href: "/job",
      },
      {
        name: "Jeremiah",
        title: "THE BOOK OF JEREMIAH",
        numberOfChapters: 52,
        href: "/jeremiah",
      },
      {
        name: "Joel",
        title: "THE BOOK OF JOEL",
        numberOfChapters: 3,
        href: "/joel",
      },
      {
        name: "Jonah",
        title: "THE BOOK OF JONAH",
        numberOfChapters: 4,
        href: "/jonah",
      },
      {
        name: "John",
        title: "THE GOSPEL ACCORDING TO JOHN",
        numberOfChapters: 21,
        href: "/john",
      },
      {
        name: "James",
        title: "THE EPISTLE OF JAMES",
        numberOfChapters: 5,
        href: "/james",
      },
      {
        name: "1 John",
        title: "THE FIRST EPISTLE OF JOHN",
        numberOfChapters: 5,
        href: "/john1",
      },
      {
        name: "2 John",
        title: "THE SECOND EPISTLE OF JOHN",
        numberOfChapters: 1,
        href: "/john2",
      },
      {
        name: "3 John",
        title: "THE THIRD EPISTLE OF JOHN",
        numberOfChapters: 1,
        href: "/john3",
      },
      {
        name: "Jude",
        title: "THE GENERAL EPISTLE OF JUDE",
        numberOfChapters: 1,
        href: "/jude",
      },
    ],
  ],
  [
    "K",
    [
      {
        name: "1 Kings",
        title: "THE FIRST BOOK OF KINGS",
        numberOfChapters: 22,
        href: "/kings1",
      },
      {
        name: "2 Kings",
        title: "THE SECOND BOOK OF KINGS",
        numberOfChapters: 25,
        href: "/kings2",
      },
    ],
  ],
  [
    "L",
    [
      {
        name: "Leviticus",
        title: "THE THIRD BOOK OF MOSES",
        numberOfChapters: 27,
        href: "/leviticus",
      },
      {
        name: "Lamentations",
        title: "THE LAMENTATIONS OF JEREMIAH",
        numberOfChapters: 5,
        href: "/lamentations",
      },
      {
        name: "Luke",
        title: "THE GOSPEL ACCORDING TO LUKE",
        numberOfChapters: 24,
        href: "/luke",
      },
    ],
  ],
  [
    "M",
    [
      {
        name: "Micah",
        title: "THE BOOK OF MICAH",
        numberOfChapters: 7,
        href: "/micah",
      },
      {
        name: "Malachi",
        title: "THE BOOK OF MALACHI",
        numberOfChapters: 4,
        href: "/malachi",
      },
      {
        name: "Matthew",
        title: "THE GOSPEL ACCORDING TO MATTHEW",
        numberOfChapters: 28,
        href: "/matthew",
      },
      {
        name: "Mark",
        title: "THE GOSPEL ACCORDING TO MARK",
        numberOfChapters: 16,
        href: "/mark",
      },
    ],
  ],
  [
    "N",
    [
      {
        name: "Numbers",
        title: "THE FOURTH BOOK OF MOSES",
        numberOfChapters: 36,
        href: "/numbers",
      },
      {
        name: "Nehemiah",
        title: "THE BOOK OF NEHEMIAH",
        numberOfChapters: 13,
        href: "/nehemiah",
      },
      {
        name: "Nahum",
        title: "THE BOOK OF NAHUM",
        numberOfChapters: 3,
        href: "/nahum",
      },
    ],
  ],
  [
    "O",
    [
      {
        name: "Obadiah",
        title: "THE BOOK OF OBADIAH",
        numberOfChapters: 1,
        href: "/obadiah",
      },
    ],
  ],
  [
    "P",
    [
      {
        name: "Psalms",
        title: "THE BOOK OF PSALMS",
        numberOfChapters: 150,
        href: "/psalms",
      },
      {
        name: "Proverbs",
        title: "THE BOOK OF PROVERBS",
        numberOfChapters: 31,
        href: "/proverbs",
      },
      {
        name: "Philippians",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO THE PHILIPPIANS",
        numberOfChapters: 4,
        href: "/philippians",
      },
      {
        name: "Philemon",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO PHILEMON",
        numberOfChapters: 1,
        href: "/philemon",
      },
      {
        name: "1 Peter",
        title: "THE FIRST EPISTLE OF PETER",
        numberOfChapters: 5,
        href: "/peter1",
      },
      {
        name: "2 Peter",
        title: "THE SECOND EPISTLE OF PETER",
        numberOfChapters: 3,
        href: "/peter2",
      },
    ],
  ],
  [
    "R",
    [
      {
        name: "Ruth",
        title: "THE BOOK OF RUTH",
        numberOfChapters: 4,
        href: "/ruth",
      },
      {
        name: "Romans",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO THE ROMANS",
        numberOfChapters: 16,
        href: "/romans",
      },
      {
        name: "Revelation",
        title: "THE REVELATION OF JESUS CHRIST",
        numberOfChapters: 22,
        href: "/revelation",
      },
    ],
  ],
  [
    "S",
    [
      {
        name: "1 Samuel",
        title: "THE FIRST BOOK OF SAMUEL",
        numberOfChapters: 31,
        href: "/samuel1",
      },
      {
        name: "2 Samuel",
        title: "THE SECOND BOOK OF SAMUEL",
        numberOfChapters: 24,
        href: "/samuel2",
      },
      {
        name: "Songs of Solomon",
        title: "THE SONGS OF SOLOMON",
        numberOfChapters: 8,
        href: "/songsofsolomon",
      },
    ],
  ],
  [
    "T",
    [
      {
        name: "1 Thessalonians",
        title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
        numberOfChapters: 5,
        href: "/thessalonians1",
      },
      {
        name: "2 Thessalonians",
        title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO THE THESSALONIANS",
        numberOfChapters: 3,
        href: "/thessalonians2",
      },
      {
        name: "1 Timothy",
        title: "THE FIRST EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
        numberOfChapters: 6,
        href: "/timothy1",
      },
      {
        name: "2 Timothy",
        title: "THE SECOND EPISTLE OF PAUL THE APOSTLE TO TIMOTHY",
        numberOfChapters: 4,
        href: "/timothy2",
      },
      {
        name: "Titus",
        title: "THE EPISTLE OF PAUL THE APOSTLE TO TITUS",
        numberOfChapters: 3,
        href: "/titus",
      },
    ],
  ],
  [
    "Z",
    [
      {
        name: "Zephaniah",
        title: "THE BOOK OF ZEPHANIAH",
        numberOfChapters: 3,
        href: "/zephaniah",
      },
      {
        name: "Zechariah",
        title: "THE BOOK OF ZECHARIAH",
        numberOfChapters: 14,
        href: "/zechariah",
      },
    ],
  ],
]);
